workflows:
  android-build:
    name: Android build (assembleDebug)
    environment:
      android:
        components:
          - platform-tools
          - build-tools-34.0.0
          - platforms;android-34
    scripts:
      - name: Build debug APK
        script: |
          echo "Trying ./gradlew assembleDebug, falling back to system gradle if needed"
          chmod +x gradlew || true
          ./gradlew assembleDebug --no-daemon -Pandroid.debug.obsoleteApi=true || gradle assembleDebug --stacktrace --info
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
